# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4943474746b3d7e823d20e400ac04a75c5733cb7f6a9c516122f7343774124b7f7043d16f3da7c2ad6c4933a953d9337d4451d574faca8debb8dc9b2373021fc

test:
  secret_key_base: abf28d5f4121ed36b6bef1d8bb493de77cf4a9b67e94069d2750cd11fc9d42210267ab0e8887327ce033df4527d0a71ad05526c100a0a340d66dee92051c2bb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
